# Created using wingetcreate

PackageIdentifier: mitmproxy.org.mitmproxy
PackageVersion: 1.0.0.0
PackageLocale: en-US
Publisher: mitmproxy.org
PackageName: mitmproxy
License: Copyright mitmproxy.org
ShortDescription: An interactive HTTP Proxy
ManifestType: defaultLocale
ManifestVersion: 1.0.0
