# Created using wingetcreate

PackageIdentifier: lightspark.Lightspark
PackageVersion: 0.8.4.1
PackageLocale: en-US
Publisher: Lightspark
PackageName: Lightspark
License: LGPL-3.0 License
ShortDescription: An alternative SWF Player
ManifestType: defaultLocale
ManifestVersion: 1.0.0
