# Created using wingetcreate

PackageIdentifier: ppy.osu
PackageVersion: 2021.524.0
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://github.com/ppy/osu/releases/download/2021.524.0/install.exe
  InstallerSha256: 2B1BA0BC65790419AC282CA56B6D7ABD145381A5259EBD67917DEA6C758CE1DA
ManifestType: installer
ManifestVersion: 1.0.0
